import nodemailer from 'nodemailer';
import type { Transporter } from 'nodemailer';

/**
 * Sends OTP emails via Gmail SMTP (or any SMTP configured in env).
 *
 * Required env for real delivery:
 *   EMAIL_USER  – Gmail address
 *   EMAIL_PASS  – Gmail App Password
 *
 * Optional:
 *   EMAIL_FROM  – display From header
 *   SMTP_HOST   – custom SMTP host
 *   SMTP_PORT   – custom SMTP port (465 or 587)
 *
 * Security:
 * - Recipient addresses are restricted to a conventional single-email format.
 * - OTPs are never written to logs in production.
 * - Nodemailer file/URL access is disabled because this mailer never needs them.
 */
export async function sendOtpEmail(
  to: string,
  otp: string,
  purpose: 'login-lock' | 'forgot-password'
): Promise<{ sent: boolean; via: 'email' | 'console'; error?: string }> {
  const recipient = to.trim();

  // This application sends OTPs to normal account email addresses.
  // Reject comments, multiple recipients and header-like input before
  // handing the value to the mail library.
  const emailPattern =
    /^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$/;

  if (recipient.length > 254 || !emailPattern.test(recipient)) {
    return {
      sent: false,
      via: 'console',
      error: 'Invalid recipient email address'
    };
  }

  // OTPs generated by the auth flow should be short numeric codes.
  // Reject unexpected markup/control characters before placing the OTP in HTML.
  if (!/^\d{4,10}$/.test(otp)) {
    return {
      sent: false,
      via: 'console',
      error: 'Invalid OTP format'
    };
  }

  const subject =
    purpose === 'forgot-password'
      ? 'Architech Alliance — Password Reset OTP'
      : 'Architech Alliance — Login Verification OTP';

  const purposeLabel =
    purpose === 'forgot-password'
      ? 'reset your password'
      : 'unlock your account after failed login attempts';

  const html = `
    <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 24px; color: #1A1918;">
      <h2 style="margin: 0 0 12px; font-size: 20px;">Architecture Alliance</h2>
      <p style="margin: 0 0 16px; color: #555;">Use this one-time code to ${purposeLabel}:</p>
      <div style="font-size: 32px; letter-spacing: 8px; font-weight: bold; background: #FAF8F5; border: 1px solid #e5e2de; border-radius: 12px; padding: 16px 20px; text-align: center;">
        ${otp}
      </div>
      <p style="margin: 16px 0 0; font-size: 13px; color: #777;">
        This code expires in <strong>10 minutes</strong>. If you did not request it, you can ignore this email.
      </p>
    </div>
  `;

  const text = `Architecture Alliance\n\nYour OTP to ${purposeLabel}: ${otp}\n\nExpires in 10 minutes.`;

  const user = process.env.EMAIL_USER?.trim();
  const pass = process.env.EMAIL_PASS?.replace(/\s+/g, '').trim();

  if (!user || !pass) {
    // Console fallback is useful locally, but never expose OTPs in production logs.
    if (process.env.NODE_ENV !== 'production') {
      console.log(`\n[OTP] ${purpose} for ${recipient}: ${otp}`);
      console.log(
        '[OTP] EMAIL_USER / EMAIL_PASS not set — OTP printed to console only.'
      );
    }

    return {
      sent: false,
      via: 'console',
      error: 'EMAIL_USER / EMAIL_PASS not set'
    };
  }

  const from =
    process.env.EMAIL_FROM?.trim() || `Architecture Alliance <${user}>`;

  if (/[\r\n]/.test(from)) {
    return {
      sent: false,
      via: 'console',
      error: 'Invalid EMAIL_FROM configuration'
    };
  }

  const customHost = process.env.SMTP_HOST?.trim();
  const envPort = process.env.SMTP_PORT ? Number(process.env.SMTP_PORT) : null;

  if (envPort !== null && (!Number.isInteger(envPort) || envPort < 1 || envPort > 65535)) {
    return {
      sent: false,
      via: 'console',
      error: 'Invalid SMTP_PORT configuration'
    };
  }

  const transports: Transporter[] = [];

  const securityOptions = {
    connectionTimeout: 15_000,
    greetingTimeout: 10_000,
    socketTimeout: 20_000,
    disableFileAccess: true,
    disableUrlAccess: true
  };

  if (customHost) {
    const port = envPort || 465;

    transports.push(
      nodemailer.createTransport({
        host: customHost,
        port,
        secure: port === 465,
        requireTLS: port === 587,
        auth: { user, pass },
        ...securityOptions
      })
    );
  } else {
    transports.push(
      nodemailer.createTransport({
        service: 'gmail',
        auth: { user, pass },
        ...securityOptions
      })
    );

    if (!envPort || envPort === 587) {
      transports.push(
        nodemailer.createTransport({
          host: 'smtp.gmail.com',
          port: 587,
          secure: false,
          requireTLS: true,
          auth: { user, pass },
          ...securityOptions
        })
      );
    }

    if (!envPort || envPort === 465) {
      transports.push(
        nodemailer.createTransport({
          host: 'smtp.gmail.com',
          port: 465,
          secure: true,
          auth: { user, pass },
          ...securityOptions
        })
      );
    }
  }

  let lastError = '';

  for (let i = 0; i < transports.length; i++) {
    try {
      await transports[i].sendMail({
        from,
        to: recipient,
        subject,
        text,
        html
      });

      console.log(
        `[OTP] Email sent to ${recipient} (${purpose}) via transport #${i + 1}`
      );

      return { sent: true, via: 'email' };
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
      console.error(`[OTP] Transport #${i + 1} failed:`, lastError);
    }
  }

  if (/Invalid login|BadCredentials|Username and Password not accepted/i.test(lastError)) {
    console.error(
      '[OTP] Gmail authentication failed. Use a Gmail App Password in EMAIL_PASS.'
    );
  } else if (/ECONNREFUSED|ETIMEDOUT|ENOTFOUND|certificate/i.test(lastError)) {
    console.error(
      '[OTP] Network/TLS issue. Check SMTP_HOST/SMTP_PORT and the server firewall.'
    );
  }

  // Never expose the OTP in production logs.
  if (process.env.NODE_ENV !== 'production') {
    console.log(`\n[OTP] FALLBACK ${purpose} for ${recipient}: ${otp}\n`);
  }

  return { sent: false, via: 'console', error: lastError };
}
